# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/redfin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),redfin)

$(call add-radio-file-sha1-checked,radio/abl.img,eeac758d76d6a85f5e6284d821299414c8e9f868)
$(call add-radio-file-sha1-checked,radio/aop.img,5e9359c167aa59cc70591118448a6f5ddbf79441)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c70c463f61337073d4066eead87ea80e79c1d692)
$(call add-radio-file-sha1-checked,radio/featenabler.img,57ce2c29958d5411f92db2e717dac7a5b3f39684)
$(call add-radio-file-sha1-checked,radio/hyp.img,664b16b372b96f6e05f66c5284522344519ad618)
$(call add-radio-file-sha1-checked,radio/keymaster.img,e0aeeaac58c3ede0a9cdc953e0bf49221c5e49cf)
$(call add-radio-file-sha1-checked,radio/modem.img,7a5a5fda473db1636599f831a1a705e6d4937c06)
$(call add-radio-file-sha1-checked,radio/qupfw.img,43a69271503fd5884a8036d3693986d035199989)
$(call add-radio-file-sha1-checked,radio/tz.img,2dd8b901d2e18b7d004508cf831d552e7caaa777)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,b7b268dfb034dcf3a22fd4b2333172b59db10d9a)
$(call add-radio-file-sha1-checked,radio/xbl.img,6d060eb8dcdb6066d9d0e0c425c06d86bf0ed141)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,26e94102fb3c997ed9c1615a4224f154d9fa53f0)

endif
