# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/redfin/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    devcfg \
    featenabler \
    hyp \
    keymaster \
    modem \
    qupfw \
    tz \
    uefisecapp \
    xbl \
    xbl_config
